### ISSUE TITLE
[Bug] Exiting Camera to return to the lock screen results in sluggish animation

### ISSUE THREAD

**Issue by guoqiyun** [Nepeta/Slyd#12]
I suspect it is due to two or more animations taking place at the same time. The exit animation and transition from notification view to the passcode screen seem to occur simultaneously. Exiting Camera should always bring the user back to the notification view (rather than passcode screen) in the first place in my opinion.

Tested on iPhone 7, iOS 11.3.1

**Comment by Nepeta** [comment]
I believe it should be fixed, report back if it isn't.
