### ISSUE TITLE
[Bug] The passcode screen remains on screen after successfully unlocking with passcode from a Home button triggered passcode screen

### ISSUE THREAD

**Issue by guoqiyun** [Nepeta/Slyd#13]
When triggering the passcode screen using the Home button, the passcode screen remains on screen after unlocking device successfully (confirmation visible in status bar). Re-entering passcode does not dismiss the passcode screen.

No Touch ID set up
Tested on iPhone 7, iOS 11.3.1

**Comment by Nepeta** [comment]
Should be fixed in 0.2.0.
