### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ikingofrandom** [Nepeta/Slyd#14]
I can’t  compile it on iOS 12.1.1b3

Phone:~/Slyd root# make package
> Making all in Tweak…
> Making all for tweak Slyd…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
clang-5.0: error: no such sysroot directory: '' [-Werror,-Wmissing-sysroot]
make[4]: *** [/var/theos/makefiles/instance/rules.mk:269: /var/root/Slyd/.theos/obj/debug/arm64/Tweak.xm.b905b62f.o] Error 1
rm /var/root/Slyd/.theos/obj/debug/arm64/Tweak.xm.mm
make[3]: *** [/var/theos/makefiles/instance/library.mk:33: /var/root/Slyd/.theos/obj/debug/arm64/Slyd.dylib] Error 2
make[2]: *** [/var/theos/makefiles/instance/library.mk:24: internal-library-all_] Error 2
make[1]: *** [/var/theos/makefiles/master/rules.mk:123: Slyd.all.tweak.variables] Error 2
make: *** [/var/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2

**Comment by Nepeta** [comment]
You're missing an SDK.
