### ISSUE TITLE
[Bug] Doesn't unlock with Touch ID or "press home to unlock"

### ISSUE THREAD

**Issue by jakeajames** [Nepeta/Slyd#7]
If I press home button or use Touch ID the device says "Unlocked" but doesn't unlock, in case of home button this happens after typing passcode.

iPad Air 2, iOS 11.3.1

**Comment by Nepeta** [comment]
@jakeajames Disable the "Disable home button" setting and try again :)

**Comment by Nepeta** [comment]
*Should* be fixed in 0.2.0. Please report back if the issue still exists, I'll close this issue in 1 week.
